### ISSUE TITLE
无法获取到chart实例

### ISSUE THREAD

**Issue by ppp1633** [lloydzhou/vuecharts#12]
在2.3.0版本直接使用useChartContext(), 获取到的值是undefined

![image](https://github.com/lloydzhou/vuecharts/assets/132039841/ecf20eeb-24c0-4c70-abbf-f55239655851)

**Comment by lloydzhou** [comment]
```
export const useChartContext = () => inject(contextSymbol)
```

`useChartContext`本质上是一个inject，所以，使用的时候需要检查一下是不是在`Chart`内部的子组件的`setup`里面。

**Comment by ppp1633** [comment]
使用的话实在Chart的外层, 实际上我是需要ehcarts实例来监听事件, 通过这种方式无法获取吗?

**Comment by lloydzhou** [comment]
按照vue文档中关于`provide`/`inject`的说明，在Chart外层是没法使用`inject`拿到数据的

**Comment by ppp1633** [comment]
嗯是这样, 那么目前组件有提供获取echarts实例的途径吗?

**Comment by lloydzhou** [comment]
你可以看看项目中的这个example

https://github.com/lloydzhou/vuecharts/blob/7ffd7fc5b5387598886b41e781ec7b63a6e2f3b7/example/App.vue#LL165C5-L165C25

```

    const chart3 = ref()
    onMounted(() => {
      console.log('chart3', chart3.value)
    })


<Chart ref="chart3">
</Chart>

```

**Comment by ppp1633** [comment]
好吧, 原来echartsInstance就在Chart组件实例里面, 谢谢你
