### ISSUE TITLE
Feature request: theme

### ISSUE THREAD

**Issue by gltjk** [lloydzhou/vuecharts#6]
Hope there is a prop on the `Chart` component that sets the theme. For instance:

希望 `Chart` 组件上能有一个属性用来设置颜色主题。例如：

```vue
<Chart theme="dark">
...
</Chart>
```

THX!

**Comment by lloydzhou** [comment]
```
<Chart theme="dark">
...
</Chart>
```
![image](https://user-images.githubusercontent.com/1826685/179403178-c8249968-28d8-4f3d-a76d-54e2f7e8dd68.png)

**Comment by gltjk** [comment]
Thanks a lot for the quick update. 十分感谢及时的更新！
